package com.miya.hw2017mobiledev.lab7;

/**
 * Created by miyag on 8/7/17.
 */

import android.content.Context;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ServerValue;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PingSource {

    DatabaseReference databaseReference = FirebaseDatabase.getInstance().getReference();
    public interface PingListener {
        void onPingsReceived(List<Ping> pingList);
    }

    private static PingSource sNewsSource;

    private Context mContext;

    public static PingSource get(Context context) {
        if (sNewsSource == null) {
            sNewsSource = new PingSource(context);
        }
        return sNewsSource;
    }

    private PingSource(Context context) {
        mContext = context;
    }

    // Firebase methods for you to implement.

    public void getPings(final PingListener pingListener) {
        DatabaseReference pingsRef = databaseReference.child("pings");
        Query last50PingsQuery = pingsRef.limitToLast(50);
        last50PingsQuery.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Iterable<DataSnapshot> pingSnapshots = dataSnapshot.getChildren();
                List<Ping> pingList = new ArrayList<Ping>();
                for (DataSnapshot pingsnap : pingSnapshots) {
                    Ping newPing = new Ping(pingsnap);
                    pingList.add(newPing);
                }
                pingListener.onPingsReceived(pingList);
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
    }

    public void getPingsForUserId(String userId, final PingListener pingListener) {

        DatabaseReference pingsRef = databaseReference.child("pings");
        Query userQuery = pingsRef.orderByChild("userId").equalTo(userId).limitToLast(50);
        userQuery.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Iterable<DataSnapshot> pingSnapshots = dataSnapshot.getChildren();
                List<Ping> pingList = new ArrayList<Ping>();
                for (DataSnapshot pingsnap : pingSnapshots) {
                    Ping newPing = new Ping(pingsnap);
                    pingList.add(newPing);
                }
                pingListener.onPingsReceived(pingList);
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

    }

    public void sendPing(Ping ping) {
        DatabaseReference pingsRef = databaseReference.child("pings");
        DatabaseReference newPingRef = pingsRef.push();//autogenerated unique key
        Map<String, Object> pingValMap = new HashMap<String, Object>();
        pingValMap.put("userName", ping.getUserName());
        pingValMap.put("userId", ping.getUserId());
        pingValMap.put("timestamp", ServerValue.TIMESTAMP);
        newPingRef.setValue(pingValMap);//sets its as value of generated key

    }
}
